### ISSUE TITLE
MPI 3 deprecates MPI_Type_struct, changes to MPI_Type_create_struct

### ISSUE THREAD

**Issue by bjoo** [usqcd-software/qmp#8]
I just tried compiling QMP with OpenMPI-4.0 and it complained about MPI_Type_struct, and instructed me to change it to MPI_Type_create_struct instead. It is a straightforward substitution, apparently the function name is all that changes. We should consider changing this as a maintainance, but in a way that we can also keep the old invocation. It only occurs once in `lib/mpi/QMP_mem_mpi.c`  as far as I can tell.

**Comment by maddyscientist** [comment]
Any reason why this issue isn't fixed yet?  As noted above by @bjoo this breaks QMP with OpenMPI 4.  `MPI_type_create_struct` was introduced in MPI-2.  I see no reason why the reference to `MPI_type_struct` can't be expunged.

**Comment by bjoo** [comment]
I changed the offending `MPI_type_struct` to `MPI_type_create_struct`. I also merged master into 'devel' to eliminate that divergence, and then merged the lot into master. If master has undesirable features, I have tagged pre and post merges. Post merge is tagged as `qmp2-5-2-rc`
